### ISSUE TITLE
The inference results do not match the expectations.

### ISSUE THREAD

**Issue by lurz01** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#17]
Hi, @JustasBart
I am using [https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX] for compilation and encountering the following issues during runtime:
 The observed results are inconsistent with expectations.
- During the inference process, only the `maxClassScore` value for the target object is normal, while other variables (`x`, `z`, `w`, `h`) are all 0.
 
![screenshot-20231206-094448](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/49187723/0db492d5-fa7a-4e77-99b8-c9950c7f817c)
## Environment Information
- Operating System: Ubuntu 20.04.5 LTS
- Compiler Version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- Dependencies: opencv4.8.0 cuda 11

"I suspect that the issue is caused by the version of OpenCV. Could you please provide the version of OpenCV?
Thank you for your assistance!

**Comment by JustasBart** [comment]
Hi @mohun895119883 we've seen something similar here https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/issues/15 with OpenCV version 4.8.0 it appears that going back to 4.7.0 might resolve your issue.

As for the OpenCV build please follow this:
![OpenCV build](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/40023722/34f9415c-731f-4f5d-9f62-227d80128c1b)

Note that since I no longer work in a Computer Vision field due to a new job opportunity I don't actively research or dwell into this sort of topic anymore and thus I've never had the change to figure this out for the latest version (4.8.0) of OpenCV...

I hope you can figure it out from here, good luck! 🚀

**Comment by lurz01** [comment]
> Hi @mohun895119883 we've seen something similar here #15 with OpenCV version 4.8.0 it appears that going back to 4.7.0 might resolve your issue.
> 
> As for the OpenCV build please follow this: ![OpenCV build](https://private-user-images.githubusercontent.com/40023722/288339074-34f9415c-731f-4f5d-9f62-227d80128c1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTI0NjEsIm5iZiI6MTcwMTkxMjE2MSwicGF0aCI6Ii80MDAyMzcyMi8yODgzMzkwNzQtMzRmOTQxNWMtNzMxZi00ZjVkLTlmNjItMjI3ZDgwMTI4YzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAxMjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYmM5NjhhYTJhY2M5NjM5YzhmOTUzYjE1MTllNjYyNTFlZjk0MTczNzdmNDM3ZTExNTg2NDU2YjYzMjk2ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6ihw-6566NOs0_6OVlZI04rVd5DDNk8NQC9XByLf-A)
> 
> Note that since I no longer work in a Computer Vision field due to a new job opportunity I don't actively research or dwell into this sort of topic anymore and thus I've never had the change to figure this out for the latest version (4.8.0) of OpenCV...
> 
> I hope you can figure it out from here, good luck! 🚀


Hi @JustasBart ! 😊Thank you for providing the version and configuration. Following your advice, I successfully resolved this issue. Wishing you all the best!

**Comment by JustasBart** [comment]
That's good to hear @mohun895119883 did you rebuild your OpenCV to 4.7.0? Or did you have to do anything else to it?

All the best! 🚀
