### ISSUE TITLE
opencv exception error while doing net.forward()

### ISSUE THREAD

**Issue by TheoLiu31** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#2]
Hey,
Thank you for your work, it's very informative to understand the output difference between yolov5 and yolov8.
However, i got this opencv error while using yolov8s.onnx:

`terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0) /home/theo/Documents/opencv-4.6.0/modules/dnn/include/opencv2/dnn/shape_utils.hpp:170: error: (-215:Assertion failed) start <= (int)shape.size() && end <= (int)shape.size() && start <= end in function 'total'`

this happens with net.forward(). I have searched a lot and someone says upgrade opencv version might resolve this problem. So I upgraded opencv version from 4.5.2 to 4.6.0, but I still got this error.

What's your opencv version to run your code successfully?
Thanks, 
Théo

**Comment by JustasBart** [comment]
Hello @TheoLiu31 here are the important bits of my '**cv::getBuildInformation()**' output that might be useful for you:

```
Version control:             4.7.0
...
Extra modules:
Location (extra):            /home/*/opencv_contrib/modules
Version control (extra):     4.7.0

Platform:
Timestamp:                   2023-*
Host:                        Linux 5.8.0-48-generic x86_64
CMake:                       3.16.3
CMake generator:             Unix Makefiles
CMake build tool:            /usr/bin/make
Configuration:               Release
...
GUI:                         QT5
QT:                          YES (ver 5.15.2 )
QT OpenGL support:           NO
GTK+:                        YES (ver 2.24.32)
GThread :                    YES (ver 2.64.6)
GtkGlExt:                    NO
VTK support:                 NO
...
NVIDIA CUDA:                 YES (ver 11.2, CUFFT CUBLAS FAST_MATH)
NVIDIA GPU arch:             35 37 50 52 60 61 70 75 80 86
NVIDIA PTX archs:

cuDNN:                       YES (ver 8.7.0)
```

Please let me know if there's anything more specific that I could help you with!

Good luck! :rocket:

**Comment by JustasBart** [comment]
@TheoLiu31 As a follow up to this, please ensure the following for your CMake build configuration:

```
BUILD_opencv_dnn             (Check)
WITH_ONNX                    (Check)
OPENCV_EXTRA_MODULES_PATH    /.../opencv_contrib/modules

# If using CUDA (Ignore if only using CPU etc...)
WITH_CUDA                    (Check)
WITH_CUDNN                   (Check)
```
Have the 'Advanced' checkbox checked if using cmake-gui (In order to configure CUDNN paths)
![image](https://user-images.githubusercontent.com/40023722/219649186-c054848b-a520-49e3-b8c6-8fce48f994e6.png)
```
CUDNN_LIBRARY                /.../cudnn-linux-x86_64-8.7.0.84_cuda11-archive/lib/libcudnn.so
CUDNN_INCLUDE_DIR            /.../cudnn-linux-x86_64-8.7.0.84_cuda11-archive/include
```
Also note that in order to have CUDA running simply looking at this isn't enough:
![image](https://user-images.githubusercontent.com/40023722/219650032-9f2d55eb-d8d6-4cd3-8cf7-dd093fc28f8d.png)

You have to have it installed where you can link to it like so:
![image](https://user-images.githubusercontent.com/40023722/219650224-55270737-7d7f-4ef9-86ec-ae7653867bc6.png)

I hope this is of any use to you :rocket:

**Comment by TheoLiu31** [comment]
@JustasBart thanks for your response. I just upgraded my opencv to 4.7.0, and problem solved.

**Comment by JustasBart** [comment]
Well done @TheoLiu31  I'm glad you were able to resolve your issue, all the best to you! :rocket:
